# Generated by Django 5.1.6 on 2026-04-13 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Исполнитель-владелец организации (внутренние чаты с сотрудниками).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
