# Generated by Django 5.1.6 on 2026-04-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_is_saved_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='is_saved_messages',
            field=models.BooleanField(default=False, help_text='Чат «Избранное» — сообщения только для себя.'),
        ),
    ]
