# Generated by Django 5.1.6 on 2026-05-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_conversationmember_last_read_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='is_saved_messages',
            field=models.BooleanField(default=False),
        ),
    ]
