"""Generate Asterisk PJSIP trunk snippets from ProviderVoiceSettings."""

from __future__ import annotations

import re
from pathlib import Path

from django.conf import settings

from .models import ProviderVoiceSettings


def _digits(phone: str) -> str:
    return re.sub(r"\D+", "", phone or "")


def _parse_sip_host(raw: str) -> tuple[str, str]:
    """Return (host, port) defaults udp/5060."""
    s = (raw or "").strip()
    s = re.sub(r"^sip:", "", s, flags=re.I)
    if "@" in s:
        s = s.split("@", 1)[1]
    host = s
    port = "5060"
    if ":" in s:
        host, port = s.rsplit(":", 1)
    return host.strip(), port.strip() or "5060"


def _endpoint_block(vs: ProviderVoiceSettings) -> str:
    pid = vs.provider_id
    host, port = _parse_sip_host(vs.sip_server)
    user = (vs.sip_username or "").strip()
    auth_user = (vs.sip_auth_user or user).strip()
    did = _digits(vs.sip_did or vs.inbound_phone)
    name = f"vmeste-p{pid}"
    lines = [
        f"; provider {pid} DID {did}",
        f"[{name}-auth]",
        "type=auth",
        "auth_type=userpass",
        f"username={auth_user}",
        f"password={vs.sip_password}",
        "",
        f"[{name}-aor]",
        "type=aor",
        "contact=",
        "max_contacts=1",
        "remove_existing=yes",
        "",
        f"[{name}-reg]",
        "type=registration",
        "transport=transport-udp",
        f"outbound_auth={name}-auth",
        f"server_uri=sip:{host}:{port}",
        f"client_uri=sip:{auth_user}@{host}",
        f"contact_user={auth_user}",
        "retry_interval=60",
        f"endpoint={name}",
        "",
        f"[{name}]",
        "type=endpoint",
        "transport=transport-udp",
        "context=from-vmeste-trunk",
        "disallow=all",
        "allow=alaw,ulaw",
        f"outbound_auth={name}-auth",
        f"aors={name}-aor",
        f"from_user={auth_user}",
        f"callerid={did}",
        "direct_media=no",
        "rtp_symmetric=yes",
        "force_rport=yes",
        "rewrite_contact=yes",
        "",
        f"[{name}-identify]",
        "type=identify",
        f"endpoint={name}",
        f"match={host}",
        "",
    ]
    return "\n".join(lines)


def sync_asterisk_configs(*, out_dir: str | Path | None = None) -> dict:
    """Write pjsip_trunks.conf + extensions_vmeste.conf; return summary."""
    base = Path(out_dir or getattr(settings, "ASTERISK_CONF_DIR", "") or "asterisk/conf/generated")
    base.mkdir(parents=True, exist_ok=True)

    qs = ProviderVoiceSettings.objects.filter(
        enabled=True,
        ats_provider=ProviderVoiceSettings.AtsProvider.ASTERISK,
    ).select_related("provider")

    blocks = []
    count = 0
    for vs in qs:
        if not vs.has_sip():
            continue
        blocks.append(_endpoint_block(vs))
        count += 1

    pjsip_path = base / "pjsip_trunks.conf"
    pjsip_path.write_text(
        "; AUTO-GENERATED by sync_voice_asterisk — do not edit\n\n" + ("\n".join(blocks) if blocks else "; no trunks\n"),
        encoding="utf-8",
    )

    ext_lines = [
        "; AUTO-GENERATED inbound routes",
        "[from-vmeste-trunk]",
        "exten => _X.,1,Gosub(vmeste-inbound,s,1(${CALLERID(num)},${EXTEN}))",
        " same => n,Hangup()",
        "",
        "[vmeste-inbound]",
        "exten => s,1,NoOp(Vmeste voice did=${ARG2} caller=${ARG1})",
        " same => n,AGI(vmeste_agi.py,${ARG2},${ARG1})",
        " same => n,Hangup()",
    ]
    ext_path = base / "extensions_vmeste.conf"
    ext_path.write_text("\n".join(ext_lines) + "\n", encoding="utf-8")

    return {"trunks": count, "pjsip_path": str(pjsip_path), "extensions_path": str(ext_path)}


def find_settings_by_did(did: str) -> ProviderVoiceSettings | None:
    """Match salon voice settings by purchased SIP number."""
    tail = _digits(did)
    if len(tail) < 10:
        return None
    for vs in ProviderVoiceSettings.objects.filter(
        enabled=True,
        ats_provider=ProviderVoiceSettings.AtsProvider.ASTERISK,
    ).select_related("provider"):
        if not vs.has_sip():
            continue
        for cand in (vs.sip_did, vs.inbound_phone):
            if _digits(cand) == tail or _digits(cand)[-10:] == tail[-10:]:
                return vs
    return None
