# Generated by Django 5.1.3 on 2026-09-06 10:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0026_booking_loyalty_discount'),
        ('catalog', '0006_serviceoption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('sku', models.CharField(blank=True, default='', max_length=64)),
                ('unit', models.CharField(blank=True, default='шт', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('attrs', models.JSONField(blank=True, default=dict, help_text='Характеристики: {ключ: значение}')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('featured_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.productcategory')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_photos/%Y/%m/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shop.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shop.productcategory')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.productsubcategory'),
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('pickup', 'Самовывоз'), ('delivery', 'Доставка')], default='pickup', max_length=20)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('assembling', 'Собирается'), ('ready', 'Готов'), ('to_courier', 'Передаём курьеру'), ('delivering', 'В пути'), ('done', 'Завершён'), ('cancelled', 'Отменён')], db_index=True, default='awaiting_payment', max_length=20)),
                ('guest_name', models.CharField(blank=True, default='', max_length=120)),
                ('guest_phone', models.CharField(blank=True, default='', max_length=32)),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254)),
                ('delivery_address', models.CharField(blank=True, default='', max_length=400)),
                ('apartment', models.CharField(blank=True, default='', max_length=32)),
                ('entrance', models.CharField(blank=True, default='', max_length=32)),
                ('intercom', models.CharField(blank=True, default='', max_length=32)),
                ('private_house', models.BooleanField(default=False)),
                ('delivery_lat', models.FloatField(blank=True, null=True)),
                ('delivery_lon', models.FloatField(blank=True, null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('items_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('courier_lat', models.FloatField(blank=True, null=True)),
                ('courier_lon', models.FloatField(blank=True, null=True)),
                ('courier_updated_at', models.DateTimeField(blank=True, null=True)),
                ('external_delivery_provider', models.CharField(blank=True, default='', max_length=20)),
                ('external_tracking_id', models.CharField(blank=True, default='', max_length=120)),
                ('yookassa_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('confirmation_url', models.URLField(blank=True, default='')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('stock_written_off', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_client_orders', to=settings.AUTH_USER_MODEL)),
                ('courier_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_courier_orders', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShopOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.shoporder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_pickup', models.BooleanField(default=True)),
                ('enable_delivery', models.BooleanField(default=False)),
                ('delivery_info', models.TextField(blank=True, default='')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_min_order', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_zones', models.JSONField(blank=True, default=list, help_text='Зоны доставки: [{id,name,color,fee,min_order,polygon:[[lat,lon],…]}]')),
                ('delivery_provider', models.CharField(choices=[('own', 'Свой курьер'), ('yandex', 'Яндекс Доставка'), ('cdek', 'СДЭК')], default='own', max_length=20)),
                ('yandex_delivery_token', models.CharField(blank=True, default='', max_length=255)),
                ('cdek_client_id', models.CharField(blank=True, default='', max_length=128)),
                ('cdek_client_secret', models.CharField(blank=True, default='', max_length=128)),
                ('accept_online_payment', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_service', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_usages', to='shop.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='catalog.service')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('service', 'product')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('in', 'Приход'), ('out_manual', 'Ручное списание'), ('out_service', 'Списание по услуге'), ('out_order', 'Списание по заказу'), ('adjust', 'Корректировка')], max_length=20)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='booking.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='shop.product')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('shop_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='shop.shoporder')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('idempotency_key',), name='uniq_stock_movement_idempotency')],
            },
        ),
    ]
