# Generated by Django 5.1.3 on 2026-09-06 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.productcategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='pool_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Ключ из пула готовых категорий (если добавлена из каталога)', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('pool_key__gt', '')), fields=('provider', 'pool_key'), name='uniq_provider_product_category_pool_key'),
        ),
    ]
