# Generated by Django 5.1.6 on 2026-04-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='recurrence_group',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
