# Generated by Django 5.1.6 on 2026-04-13 07:42

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_providerstaff_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerstaff',
            name='permissions',
            field=models.JSONField(blank=True, default=booking.models.default_staff_permissions),
        ),
    ]
