# Generated by Django 5.1.3 on 2026-08-21 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_new_booking_template'),
        ('catalog', '0006_serviceoption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providermessagingsettings',
            name='winback_enabled',
            field=models.BooleanField(default=False, help_text='Напоминать клиентам, которые давно не были.'),
        ),
        migrations.AddField(
            model_name='providermessagingsettings',
            name='winback_template',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='providermessagingsettings',
            name='winback_weeks',
            field=models.PositiveSmallIntegerField(default=4, help_text='Сколько недель без визита, чтобы отправить напоминание.'),
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_balances', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('provider', 'client')},
            },
        ),
        migrations.CreateModel(
            name='LoyaltyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='booking.loyaltyaccount')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_entries', to='booking.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('points_per_visit', models.PositiveIntegerField(default=1, help_text='Баллы за каждый завершённый визит.')),
                ('points_per_100_rub', models.PositiveIntegerField(default=0, help_text='Доп. баллы за каждые 100 ₽ чека (0 — выкл).')),
                ('rub_per_point', models.DecimalField(decimal_places=2, default=1, help_text='Сколько рублей скидки даёт 1 балл при списании.', max_digits=8)),
                ('welcome_bonus', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('visits_count', models.PositiveSmallIntegerField(default=5)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('validity_days', models.PositiveSmallIntegerField(blank=True, help_text='Срок действия с покупки, дней. Пусто — без срока.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_packages', to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(blank=True, help_text='Пусто — любой визит к этой организации.', related_name='visit_packages', to='catalog.service')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits_total', models.PositiveSmallIntegerField()),
                ('visits_remaining', models.PositiveSmallIntegerField()),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('exhausted', 'Израсходован'), ('expired', 'Истёк'), ('cancelled', 'Отменён')], default='active', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=250)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_packages', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_packages', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='booking.visitpackage')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='WinbackReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sent_at', models.DateTimeField(auto_now=True)),
                ('weeks_at_send', models.PositiveSmallIntegerField(default=4)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winback_received', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winback_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('provider', 'client')},
            },
        ),
    ]
