# Generated by Django 5.1.3 on 2026-08-23 10:34

import django.db.models.deletion
import voice.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0024_booking_status_arrived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderVoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('webhook_token', models.CharField(default=voice.models._voice_webhook_token, max_length=64, unique=True)),
                ('inbound_phone', models.CharField(blank=True, default='', help_text='Номер салона для сопоставления входящих (опционально).', max_length=32)),
                ('transfer_phone', models.CharField(blank=True, default='', help_text='Перевод на живого администратора.', max_length=32)),
                ('greeting_text', models.TextField(blank=True, default='Здравствуйте! Это голосовой администратор. Помогу записаться на услугу. Скажите, что вас интересует.')),
                ('ats_provider', models.CharField(choices=[('generic', 'Generic JSON'), ('mango', 'Mango Office'), ('novofon', 'Novofon / UIS')], default='generic', max_length=16)),
                ('confirm_outbound_enabled', models.BooleanField(default=False, help_text='Исходящие звонки для подтверждения записи (фаза 2).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceCallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_call_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('caller_phone', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершён'), ('transferred', 'Перевод'), ('failed', 'Ошибка')], default='active', max_length=16)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_sessions', to='booking.booking')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceCallTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Клиент'), ('assistant', 'Ассистент'), ('system', 'Система'), ('tool', 'Инструмент')], max_length=16)),
                ('text', models.TextField(blank=True, default='')),
                ('tool_name', models.CharField(blank=True, default='', max_length=64)),
                ('tool_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='voice.voicecallsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
