# Generated by Django 5.1.3 on 2026-08-23 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_booking_status_arrived'),
        ('voice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providervoicesettings',
            name='mango_api_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='providervoicesettings',
            name='mango_api_salt',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='providervoicesettings',
            name='mango_extension',
            field=models.CharField(blank=True, default='', help_text='Внутренний добавочный (опционально).', max_length=16),
        ),
        migrations.AddField(
            model_name='providervoicesettings',
            name='mango_line_number',
            field=models.CharField(blank=True, default='', help_text='Исходящая линия Mango (номер салона).', max_length=32),
        ),
        migrations.CreateModel(
            name='VoiceOutboundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('dialing', 'Набор'), ('done', 'Завершён'), ('failed', 'Ошибка')], default='queued', max_length=16)),
                ('external_command_id', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_outbound_logs', to='booking.booking')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_outbound_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_logs', to='voice.voicecallsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
