# Generated by Django 5.1.3 on 2026-08-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_mango_outbound'),
    ]

    operations = [
        migrations.AddField(
            model_name='providervoicesettings',
            name='tts_enabled',
            field=models.BooleanField(default=False, help_text='Озвучивать ответы через Yandex SpeechKit (поле say_audio_base64 в webhook).'),
        ),
    ]
