# Generated by Django 5.1.3 on 2026-09-05 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoyNalogAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(blank=True, default='', max_length=12)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('device_id', models.CharField(blank=True, default='', max_length=64)),
                ('access_token_enc', models.TextField(blank=True, default='')),
                ('refresh_token_enc', models.TextField(blank=True, default='')),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True, help_text='Автовыдача чеков при оплате')),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moy_nalog_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Мой налог: аккаунт',
                'verbose_name_plural': 'Мой налог: аккаунты',
            },
        ),
        migrations.CreateModel(
            name='NpdReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('booking', 'Запись'), ('cafe_order', 'Заказ кафе'), ('manual', 'Вручную')], max_length=16)),
                ('source_id', models.PositiveBigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('none', 'Нет'), ('pending', 'В процессе'), ('issued', 'Выбит'), ('failed', 'Ошибка'), ('maybe', 'Неизвестно (нужна проверка)'), ('cancelled', 'Аннулирован')], db_index=True, default='none', max_length=16)),
                ('receipt_uuid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('receipt_url', models.URLField(blank=True, default='')),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('operation_time', models.DateTimeField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npd_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Мой налог: чек',
                'verbose_name_plural': 'Мой налог: чеки',
                'indexes': [models.Index(fields=['provider', '-created_at'], name='moy_nalog_n_provide_7a6386_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_id'), name='uniq_npd_receipt_source')],
            },
        ),
    ]
