# Generated by Django 5.1.6 on 2026-05-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booking_cancel_message_default',
            field=models.TextField(blank=True, default='', help_text='Сообщение клиенту при отмене записи организацией.'),
        ),
        migrations.AddField(
            model_name='user',
            name='booking_confirm_message_default',
            field=models.TextField(blank=True, default='', help_text='Сообщение клиенту при подтверждении записи.'),
        ),
    ]
