# Generated by Django 5.1.3 on 2026-08-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_marketplaces_sphere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_user_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='MAX user id после привязки.', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider_sphere',
            field=models.CharField(blank=True, choices=[('hair_salon', 'Салон красоты'), ('service_center', 'Автосервис'), ('cafe_restaurant', 'Кафе и рестораны'), ('marketplaces', 'Маркетплейсы')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Telegram chat_id после /start у бота организации или платформы.', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='vk_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ID VK ID (вход через VK, ОК или Mail).', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='yandex_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ID аккаунта Яндекс ID.', max_length=64),
        ),
    ]
